Updating wolox eslint version
Wolox/eslint-config-wolox-react pull request #7
Opened 2019-09-30 17:43 UTC by raparicio6

I am also adding `prettier-eslint` package since is required in Wolox linter https://github.com/Wolox/eslint-config-wolox/blob/master/package.json#L17 but it wasnt here

2019-09-30 17:51 UTC, pabloferro requested changes

2019-09-30 17:51 UTC, pabloferro commented on README.md
> +**eslint-config-wolox-node** is available under the MIT [license](LICENSE.md).
```suggestion
**eslint-config-wolox-react** is available under the MIT [license](LICENSE.md).
```

2019-09-30 17:52 UTC, raparicio6 commented on README.md
> +**eslint-config-wolox-node** is available under the MIT [license](LICENSE.md).
lol

2019-10-08 22:16 UTC, raparicio6 commented
@pabloferro @damfinkel don't forget me :cry:

2019-10-23 19:35 UTC, damfinkel approved these changes

2019-10-23 19:46 UTC, pabloferro approved these changes

2019-12-26 13:37 UTC, damfinkel requested changes
prettier-eslint is [deprecated](https://github.com/prettier/prettier-vscode/issues/958) , I'll close this PR

2019-12-26 13:37 UTC, closed without merging